### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by jjanderson** [WetwareLabs/docker-openhab2#5]

**Comment by WetwareLabs** [comment]
Hi there!

Thanks for reaching out. I haven't been tinkering with Docker for a 
while now, and I've just used very old Docker Openhab 2 image that has 
been running quite nicely in the background.

It seems building the Docker image manually fails with the current 
Openhab version, so I have to look into that, but my old image should 
work. Also there's now official Docker image from guys at Openhab
available ( https://hub.docker.com/r/openhab/openhab/ ) so you could try 
that. Although it is of course bleeding edge, but should have more 
community support :)

What problems do you have with your installation, can you elaborate?

Best regards,
Marcus

**Comment by jjanderson** [comment]
Hi Marcus,

 

Thanks for getting back to me.

 

I have managed to get as far as seeing the image and container in docker as per images below. This is however where I am stuck. I tried to run the build commands in the terminal section of the first screen below, but then tried to go to IP:8080 etc but could not see anything. 

 

I am new to docker and not by any means an expert in terminal or linux.

 

Let me try the build at the location you pointed me to and take it from there.



 



 

Thanks again for any help. Would you be open to me simply paying you to get a stable build of version 2 up and running when it is out of beta?

 

Thanks,

 

JJ
