### ISSUE TITLE
Example in the readme is not working

### ISSUE THREAD

**Issue by xavierh** [WetwareLabs/docker-openhab2#7]
To access the demo, according to the readme:
http://[IP-of-Docker-Host]:8080/openhab.app?sitemap=demo

This does not work for me:
HTTP ERROR 404

Problem accessing /openhab.app. Reason:

```
ProxyServlet: /openhab.app
```

**Comment by WetwareLabs** [comment]
Hi Xavierh,

I haven't been maintaining this repository for almost a year now and its definitely deprecated and building it will fail.  However there's the official Docker repo from OpenHab people here  [https://hub.docker.com/r/openhab/openhab/] so I advice you to try that out first. They have also more community support in case of trouble :)

Br,
Marcus
